# Generated by Django 3.1.3 on 2020-11-13 04:37

from django.db import migrations, models
import django.db.models.deletion
import myinfo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ClientReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(blank=True, max_length=120, null=True)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('company', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(blank=True, max_length=120, null=True)),
                ('institute', models.CharField(blank=True, max_length=120, null=True)),
                ('year1', models.DateField(auto_now=True)),
                ('year2', models.DateField(auto_now=True)),
                ('dept', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('navbar', models.CharField(blank=True, max_length=120, null=True)),
                ('pro_picture', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('myname', models.CharField(blank=True, max_length=120, null=True)),
                ('my_title', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_no', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=120, null=True)),
                ('social_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecentPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('tag', models.CharField(blank=True, max_length=120, null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ImageField(blank=True, null=True, upload_to=myinfo.models.upload_location)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=120, null=True)),
                ('institute', models.CharField(blank=True, max_length=120, null=True)),
                ('year1', models.DateField(auto_now=True)),
                ('year2', models.DateField(auto_now=True)),
                ('responsibility1', models.CharField(blank=True, max_length=120, null=True)),
                ('responsibility2', models.CharField(blank=True, max_length=120, null=True)),
                ('responsibility3', models.CharField(blank=True, max_length=120, null=True)),
                ('responsibility4', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_link', models.URLField(blank=True, null=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='myinfo.home')),
            ],
        ),
    ]
