# Generated by Django 3.1.3 on 2020-11-13 06:21

from django.db import migrations, models
import myinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=myinfo.models.upload_location),
        ),
    ]
