# Generated by Django 3.1.3 on 2020-11-13 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0002_about_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='myname',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.URLField(blank=True, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='myinfo.about')),
            ],
        ),
    ]
