# Generated by Django 3.1.3 on 2020-11-13 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0003_auto_20201113_0745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
