# Generated by Django 3.1.3 on 2020-11-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0004_auto_20201113_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resume/'),
        ),
        migrations.AlterField(
            model_name='clientreviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Client/'),
        ),
        migrations.AlterField(
            model_name='professionalskill',
            name='skill',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='recentportfolio',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='skill',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
