# Generated by Django 3.1.3 on 2020-11-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0006_auto_20201113_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='icon',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
