# Generated by Django 3.1.3 on 2020-11-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0007_about_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskill',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='technicalskill',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
