# Generated by Django 3.1.3 on 2020-11-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0008_auto_20201114_0615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalskill',
            name='percentage',
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='skill/'),
        ),
    ]
