# Generated by Django 3.1.3 on 2020-11-14 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0009_auto_20201114_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionalskill',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='skill/'),
        ),
    ]
