# Generated by Django 3.1.3 on 2020-11-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0010_auto_20201114_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='education',
            name='year2',
            field=models.DateField(),
        ),
    ]
