# Generated by Django 3.1.3 on 2020-11-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0011_auto_20201114_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='year2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
