# Generated by Django 3.1.3 on 2020-11-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0012_auto_20201114_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='year1',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='year2',
            field=models.DateField(blank=True, null=True),
        ),
    ]
