# Generated by Django 3.1.3 on 2020-11-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0013_auto_20201114_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='RPTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=120, null=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rptags', to='myinfo.recentportfolio')),
            ],
        ),
    ]
