# Generated by Django 3.1.3 on 2020-11-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0014_rptag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rptag',
            old_name='about',
            new_name='recentportfolio',
        ),
    ]
