# Generated by Django 3.1.3 on 2020-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0017_auto_20201114_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='contact_no',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
