# Generated by Django 3.1.3 on 2020-11-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0018_auto_20201114_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='contact_no',
        ),
    ]
