# Generated by Django 3.1.3 on 2020-11-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0025_home_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
