# Generated by Django 3.1.3 on 2020-11-15 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0026_sociallink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalskill',
            name='image',
        ),
        migrations.AddField(
            model_name='professionalskill',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
