# Generated by Django 3.1.3 on 2020-11-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0027_auto_20201115_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientreviews',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='Client/'),
        ),
    ]
